server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emp_management?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    date-format-property:
      com.example.emp.entity.Employee.entryDate: yyyy-MM-dd

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.emp.entity
  configuration:
    map-underscore-to-camel-case: true